runtime: nodejs20
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  NODE_ENV: 'production'
  # Add your API keys here or in the Google Cloud Console secrets
  # API_KEY: '...'
